bio/config/routes.rb
Rails.application.routes.draw do
  resources :biographies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bio/app/models/biography.rb
class Biography < ApplicationRecord
end

bio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bio/app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
  before_action :set_biography, only: [:show, :edit, :update, :destroy]

  # GET /biographies
  # GET /biographies.json
  def index
    @biographies = Biography.all
  end

  # GET /biographies/1
  # GET /biographies/1.json
  def show
  end

  # GET /biographies/new
  def new
    @biography = Biography.new
  end

  # GET /biographies/1/edit
  def edit
  end

  # POST /biographies
  # POST /biographies.json
  def create
    @biography = Biography.new(biography_params)

    respond_to do |format|
      if @biography.save
        format.html { redirect_to @biography, notice: 'Biography was successfully created.' }
        format.json { render :show, status: :created, location: @biography }
      else
        format.html { render :new }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biographies/1
  # PATCH/PUT /biographies/1.json
  def update
    respond_to do |format|
      if @biography.update(biography_params)
        format.html { redirect_to @biography, notice: 'Biography was successfully updated.' }
        format.json { render :show, status: :ok, location: @biography }
      else
        format.html { render :edit }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biographies/1
  # DELETE /biographies/1.json
  def destroy
    @biography.destroy
    respond_to do |format|
      format.html { redirect_to biographies_url, notice: 'Biography was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biography
      @biography = Biography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biography_params
      params.require(:biography).permit(:name, :biography)
    end
end

bio/app/helpers/application_helper.rb
module ApplicationHelper
end

bio/app/helpers/biographies_helper.rb
module BiographiesHelper
end

bio/app/views/biographies/_form.html.erb
<%= form_with(model: biography, local: true) do |form| %>
  <% if biography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(biography.errors.count, "error") %> prohibited this biography from being saved:</h2>

      <ul>
        <% biography.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :biography %>
    <%= form.text_field :biography %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bio/app/views/biographies/edit.html.erb
<h1>Editing Biography</h1>

<%= render 'form', biography: @biography %>

<%= link_to 'Show', @biography %> |
<%= link_to 'Back', biographies_path %>

bio/app/views/biographies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Biographies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Biography</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @biographies.each do |biography| %>
      <tr>
        <td><%= biography.name %></td>
        <td><%= biography.biography %></td>
        <td><%= link_to 'Show', biography %></td>
        <td><%= link_to 'Edit', edit_biography_path(biography) %></td>
        <td><%= link_to 'Destroy', biography, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biography', new_biography_path %>

bio/app/views/biographies/new.html.erb
<h1>New Biography</h1>

<%= render 'form', biography: @biography %>

<%= link_to 'Back', biographies_path %>

bio/app/views/biographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @biography.name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @biography.biography %>
</p>

<%= link_to 'Edit', edit_biography_path(@biography) %> |
<%= link_to 'Back', biographies_path %>

bio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>